name: Update GitHub Profile README
on:
  push:
  schedule:
    - cron: "*/10 * * * *" 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Profile Readme Stats
      uses: teoxoy/profile-readme-stats@v1.2
      with:
    # Personal access token with `read:user` scope and optional `repo` scope
         token: ${{ secrets.GH_TOKEN }}
      
      
